import type { Metadata } from "next";
import { PageBanner } from "@/components/sections/PageBanner";
import { LegalBody } from "@/components/sections/LegalBody";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${site.legalName} handles the information submitted through this website.`,
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <PageBanner
        eyebrow="Legal"
        title="Privacy Policy"
        description={`How ${site.legalName} collects, uses and retains the information you submit through this website.`}
        crumbs={[
          { label: "Home", href: "/" },
          { label: "Company" },
          { label: "Privacy Policy" },
        ]}
      />

      <LegalBody
        sections={[
          {
            heading: "Information we collect",
            paragraphs: [
              "When you submit an enquiry through this website we collect the details you provide: your name, company, business email address, phone number, the requirement you select and any message you write.",
              "We also collect standard technical information generated by your browser when you visit, such as pages requested and approximate location derived from your IP address.",
            ],
          },
          {
            heading: "How we use it",
            paragraphs: [
              "Enquiry details are used to respond to your request — to prepare a configuration, ask clarifying questions or arrange a call. We do not sell your information, and we do not share it with third parties except where a specific supplier or manufacturer needs it to quote or fulfil your requirement.",
            ],
          },
          {
            heading: "Retention",
            paragraphs: [
              "We keep enquiry records for as long as needed to serve the commercial relationship and to meet applicable record-keeping obligations. You can ask us to delete your details at any time.",
            ],
          },
          {
            heading: "Your choices",
            paragraphs: [
              `To request a copy of the information we hold about you, to correct it, or to have it deleted, write to ${site.contact.email}.`,
            ],
          },
          {
            heading: "Changes to this policy",
            paragraphs: [
              "We may update this policy as our practices or legal obligations change. The current version is always the one published on this page.",
            ],
          },
        ]}
      />
    </>
  );
}
